Updating sf_cli_integration.yml

diff --git a/.github/workflows/sf_cli_integration.yml b/.github/workflows/sf_cli_integration.yml
--- a/.github/workflows/sf_cli_integration.yml
+++ b/.github/workflows/sf_cli_integration.yml
@@ -200,6 +200,10 @@ jobs:
           echo "::error::testFunction/.datacustomcode_proj/sdk_config.json not found after function init."
           exit 1
         }
+        test -f testFunction/payload/tests/test.json || {
+          echo "::error::testFunction/payload/tests/test.json not found after function init."
+          exit 1
+        }
 
       # ── Function: scan ────────────────────────────────────────────────────────
 
@@ -251,7 +255,7 @@ jobs:
 
       # ── Function: run ─────────────────────────────────────────────────────────
 
-    - name: '[function] run — sf data-code-extension function run --entrypoint testFunction/payload/entrypoint.py -o dev1'
+    - name: '[function] run — sf data-code-extension function run --entrypoint testFunction/payload/entrypoint.py  --test_with testFunction/payload/tests/test.json -o dev1'
       run: |
         sf data-code-extension function run \
           --entrypoint testFunction/payload/entrypoint.py \
